### PR TITLE
Keep paths as Path for `ws changes`

### LINKED ISSUE #7: ws changed is failing to find changes (on Windows?)
Running against CAD97/pointer-utils@4b286e1

```powershell
PS D:\repos\cad97\pointer-utils> git tag
erasable@1.2.1
ptr-union@2.0.1
rc-borrow@1.2.1
rc-box@1.1.1
slice-dst@1.4.1
PS D:\repos\cad97\pointer-utils> cargo ws ll
erasable  v1.2.1 crates\erasable
ptr-union v2.0.1 crates\ptr-union
rc-borrow v1.2.1 crates\rc-borrow
rc-box    v1.1.1 crates\rc-box
slice-dst v1.4.1 crates\slice-dst
PS D:\repos\cad97\pointer-utils> cargo ws changed
info looking for changes since erasable@1.2.1
PS D:\repos\cad97\pointer-utils> cargo ws --version
cargo-workspaces 0.2.1
```

even though there definitely have been changes since the last publish (in ptr-union and rc-borrow): https://github.com/CAD97/pointer-utils/compare/erasable@1.2.1...4b286e1

### PR DESCRIPTION
**Pull request by CAD97**
This fixes #7, which was due to path separator mismatches.

### CODE REVIEW

File: cargo-workspaces/src/utils/pkg.rs [hunk 1]
```diff
@@ -46,19 +46,17 @@ impl Listable for Vec<Pkg> {
             let mut width = first - pkg.name.len();
 
             if list.long {
-                let path = if pkg.path.is_empty() { "." } else { &pkg.path };
```
Comment (pksunkara) [inline cargo-workspaces/src/utils/pkg.rs:49]: Removing this line has failed the tests.

Comment (CAD97) [reply cargo-workspaces/src/utils/pkg.rs:49]: I re-added the check to replace the empty path with `.`.
